version: "3"
services:
  #PHP SERVICE
    matcher-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: matcher-app
        container_name: matcher-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAG: dev
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - matcher-network
        depends_on:
            - matcher-mysql-db


#NGINX WEBESRVER
    matcher-nginx:
        image: nginx:alpine
        container_name: matcher-nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8081:80
            - 4431:443
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - matcher-network

#MYSQL SERVICE
    matcher-mysql-db:
        image: mysql:8.0.27
        container_name: matcher-mysql-db
        restart: unless-stopped
        tty: true
        ports:
            - 33061:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_NAME: mysql
            SERVICE_TAG: dev
        volumes:
            - dbdata:/var/lib/mysql-files
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - matcher-network

    #MYSQL SERVICE
    matcher-mysql-db-test:
        image: mysql:8.0.27
        container_name: matcher-mysql-db-test
        restart: unless-stopped
        tty: true
        ports:
            - 33062:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE_TEST}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_TEST}
            SERVICE_NAME: mysql
            SERVICE_TAG: dev
        networks:
            - matcher-network

networks:
  matcher-network:
    driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local

